.deploy: &deploy
  stage: deploy
  cache:
    # speed up packaging by sharing cache amongst multiple deploy jobs of the same commit
    key: "deploy-$CI_COMMIT_SHORT_SHA"
    paths:
      - platforms/
      - plugins/
  before_script:
    # workaround Xcode not downloading updated profiles
    - rm -fr ~/Library/MobileDevice/Provisioning\ Profiles/
    - echo "$BUILD_CONFIG" | tr -d '\r' > build.json
    - docker info
  after_script:
    - rm build.json
    - cp $OUTPUT_PATH.$FILE_TYPE $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$FILE_TYPE
  artifacts:
    name:
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$FILE_TYPE
    expire_in: 7 days
  tags:
    - app-tag
  when: manual

deploy:android:debug:
  <<: *deploy
  environment:
    name: production
  variables:
    PLATFORM: android
    FILE_TYPE: apk
    OUTPUT_PATH: platforms/android/app/build/outputs/apk/debug/app-debug
  script:
    - npm ci
    - ionic cordova platform rm android
    - ionic cordova platform add android
    - ionic cordova build android --debug
deploy:android:release:
  <<: *deploy
  environment:
    name: production
  variables:
    PLATFORM: android
    FILE_TYPE: apk
    OUTPUT_PATH: platforms/android/app/build/outputs/apk/release/app-release
  script:
    - npm ci
    - ionic cordova platform rm android
    - ionic cordova platform add android
    - ionic cordova build android --release
  image: alpine:latest
